version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    restart: always
    environment:
      - OLLAMA_HOST=host.docker.internal
      - OLLAMA_PORT=11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
